### Corresponding Rmd for SCM.stan
#### Started on 27/06/2026


Will include data formatting, pre_var function, data list, model compiling, model fitting, convergence checks (?), coefficient extraction, intervention effects, and some plots.



**Libraries**
```{r}
library(cmdstanr)
library(posterior)
library(tidyverse)
library(patchwork)
library(bayesplot)
library(ggplot2)
library(EValue)
```

**Dataset**
```{r}
data <- read.csv("data.csv")
df <- data
#avoiding full 1
df <- df |>
  mutate(biofouling = if_else(
    biofouling == 0, 
    0,                                             
    (biofouling * (n() - 1) + 0.5) / n()           
  ))
# 0-1 zib can only handle 0-1
df$biofouling <- df$biofouling / 100

#2 most important zooplankton
df <- df %>%
  mutate(pred_zoo = copepoda + arrow_worm)
#temporary
df <- df %>% 
  mutate(nutrients =  NO2_um + NO3_um + PO4_um)

df <- df %>%
  rename(current = current_velocity_w17) %>%
  rename(seaweed_growth = blade_length) %>%
  rename(salinity = Salinity) %>%
  rename(precipitation = precipitation_mm_w17) %>%
  rename(daylight = daylight_duration_h_w17) %>%
  rename(sst = sea_surface_temperature_c_w17) %>%
  rename(phyto = total_phytoplankton) %>%
  rename(cyphonautes = cyphonaute) %>%
  rename(air_temp = avg_temp_w17)

#scaling
df <- df |>
  mutate(across(c(nutrients, phyto, seaweed_growth, current,
                  air_temp, sst, daylight, salinity,
                  pred_zoo, precipitation, cyphonautes),
                ~ scale(.)[,1]))
```

```{r}
#Splits each variable into its missing and observed values
#helps with imputation
prep_var <- function(x) {
  obs_idx  <- which(!is.na(x))
  miss_idx <- which(is.na(x))
  list(
    n_obs    = length(obs_idx),
    n_miss   = length(miss_idx),
    obs_idx  = obs_idx,
    miss_idx = miss_idx,
    obs_vals = x[obs_idx],
    imp_mean = mean(x, na.rm = TRUE),
    imp_sd   = sd(x,   na.rm = TRUE)
  )
}

```

**'Preparing' Variables**
```{r}
pv_airtemp <- prep_var(df$air_temp)
pv_current <- prep_var(df$current)
pv_daylight <- prep_var(df$daylight)
pv_precip <- prep_var(df$precipitation)
pv_predzoo <- prep_var(df$pred_zoo)
pv_sst <- prep_var(df$sst)
pv_sal <- prep_var(df$salinity)
pv_nut <- prep_var(df$nutrients)
pv_seaweed <- prep_var(df$seaweed_growth)
pv_phyto <- prep_var(df$phyto)
pv_cyph <- prep_var(df$cyphonautes)
```

**Intervention grid shtuff**
```{r}
N_interv <- 11 
interv_grid <- seq(-1, 1, length.out = N_interv) #range of interventions
```



**Model datalist**
```{r}
stan_data <- list(
  N = nrow(df),
  #random effectss
  J_farm = max(df$farm),
  J_replicate = max(df$replicate),
  farm_id    = as.integer(factor(df$farm)),
  replicate_id = as.integer(factor(df$replicate)),
  
  #response
  biofouling = df$biofouling,
  
  #exposure nodes -
  #starting w/ root nodes
  
  #Air Temperature
  N_airtemp_obs = pv_airtemp$n_obs,
  N_airtemp_miss = pv_airtemp$n_miss,
  airtemp_obs_idx = pv_airtemp$obs_idx,
  airtemp_miss_idx = pv_airtemp$miss_idx,
  airtemp_obs = pv_airtemp$obs_vals,
  imp_airtemp_mean = pv_airtemp$imp_mean, #nodes w/o parents impute from air_temp dis and not function
  imp_airtemp_sd = pv_airtemp$imp_sd,
  
  #Daylight
  N_daylight_obs = pv_daylight$n_obs,
  N_daylight_miss = pv_daylight$n_miss,
  daylight_obs_idx = pv_daylight$obs_idx,
  daylight_miss_idx = pv_daylight$miss_idx,
  daylight_obs = pv_daylight$obs_vals,
  imp_daylight_mean = pv_daylight$imp_mean,
  imp_daylight_sd = pv_daylight$imp_sd,
  
  #Current
  N_current_obs = pv_current$n_obs,
  N_current_miss = pv_current$n_miss,
  current_obs_idx = pv_current$obs_idx,
  current_miss_idx = pv_current$miss_idx, 
  current_obs = pv_current$obs_vals,
  imp_current_mean = pv_current$imp_mean, 
  imp_current_sd = pv_current$imp_sd,
  
  #Precipitation 
  N_precip_obs = pv_precip$n_obs,
  N_precip_miss = pv_precip$n_miss,
  precip_obs_idx = pv_precip$obs_idx,
  precip_miss_idx = pv_precip$miss_idx,
  precip_obs = pv_precip$obs_vals, 
  imp_precip_mean = pv_precip$imp_mean,
  imp_precip_sd = pv_precip$imp_sd,
  
  #Predatory zooplankton
  N_predzoo_obs = pv_predzoo$n_obs,
  N_predzoo_miss = pv_predzoo$n_miss,
  predzoo_obs_idx = pv_predzoo$obs_idx,
  predzoo_miss_idx = pv_predzoo$miss_idx,
  imp_predzoo_mean = pv_predzoo$imp_mean,
  imp_predzoo_sd = pv_predzoo$imp_sd,
  predzoo_obs = pv_predzoo$obs_vals,
  
  #Sea surface temperature 
  N_sst_obs = pv_sst$n_obs,
  N_sst_miss = pv_sst$n_miss,
  sst_obs_idx = pv_sst$obs_idx,
  sst_miss_idx = pv_sst$miss_idx,
  sst_obs = pv_sst$obs_vals,
  
  #Salinity
  N_sal_obs = pv_sal$n_obs,
  N_sal_miss = pv_sal$n_miss,
  sal_obs_idx = pv_sal$obs_idx,
  sal_miss_idx = pv_sal$miss_idx,
  sal_obs = pv_sal$obs_vals,
  
  #Nutrients - NO3 + NO2 + PO4
  N_nut_obs = pv_nut$n_obs,
  N_nut_miss = pv_nut$n_miss,
  nut_obs_idx = pv_nut$obs_idx,
  nut_miss_idx = pv_nut$miss_idx,
  nut_obs = pv_nut$obs_vals,
  
  #Seaweed growth 
  N_seaweed_obs = pv_seaweed$n_obs,
  N_seaweed_miss = pv_seaweed$n_miss,
  seaweed_obs_idx = pv_seaweed$obs_idx,
  seaweed_miss_idx = pv_seaweed$miss_idx,
  seaweed_obs = pv_seaweed$obs_vals,
  
  #Phytoplankton
  N_phyto_obs = pv_phyto$n_obs,
  N_phyto_miss = pv_phyto$n_miss,
  phyto_obs_idx = pv_phyto$obs_idx,
  phyto_miss_idx = pv_phyto$miss_idx,
  phyto_obs = pv_phyto$obs_vals,
  
  #Cyphonautes
  N_cyph_obs = pv_cyph$n_obs,
  N_cyph_miss = pv_cyph$n_miss,
  cyph_obs_idx = pv_cyph$obs_idx,
  cyph_miss_idx = pv_cyph$miss_idx,
  cyph_obs = pv_cyph$obs_vals,
  
  #Intervention grids - carrying over gcomp stuff from causal model
  N_interv = N_interv,
  do_airtemp = interv_grid,
  do_current = interv_grid,
  do_daylight = interv_grid,
  do_precip = interv_grid,
  do_predzoo = interv_grid,
  do_sst = interv_grid,
  do_nutrients = interv_grid,
  do_seaweed = interv_grid,
  do_phyto = interv_grid
) 
```

